### ISSUE TITLE
Missing 4 and 5

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#1]
Unable to download [4. Views](https://itunesu-assets.itunes.apple.com/apple-assets-us-std-000001/CobaltPublic82/v4/2f/19/00/2f190095-0ad9-68da-de79-460b9b9a5b21/307-1808792045946883749-04_1_23_17_1080p_1_720p_3000.m4v) and [5. Gestures and Multiple MVCs](https://itunesu-assets.itunes.apple.com/apple-assets-us-std-000001/CobaltPublic122/v4/3b/e8/87/3be887ea-089b-2532-81eb-3f21a789d79c/328-6978379452515215276-05_1_25_17_720p_3000cc.m4v). Server returns `An error occurred while processing your request.`

If you cached these episodes previously, please help. If you have no clue how to extract CC from m4v file, use CCExtractor(`brew install ccextractor`)

**Comment by ApolloZhu** [comment]
能帮下忙么，@buginux，百度云上的已经没有字幕了...

**Comment by l5ee** [comment]
感谢大神的无私，英文太差帮不了什么忙。。。正在零基础开始学习swift开发

**Comment by devImpChen** [comment]
感动。英语太差帮不上什么忙，感谢参与过翻译的大神们
