### ISSUE TITLE
「任务分配」5. Gestures and Multiple MVCs.srt

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#19]
|字幕序号|翻译人员|状态|校对人员|状态|
|--|--|--|--|--|
|4-42|@CrowsStriker|已完成||待认领|
|43-599|@ApolloZhu|已完成||待认领|
|600-1093|@superk589|已完成||待认领|
|1094-1399|@VoiceBeer|已完成||待认领|
|1400-1656|@CrowsStriker|已完成||待认领|
|1657-1836|@ApolloZhu|已完成||待认领|

**Comment by VoiceBeer** [comment]
@ApolloZhu 1094-1836 我可以翻

**Comment by ApolloZhu** [comment]
好，谢谢了

**Comment by VoiceBeer** [comment]
谢谢你才对，提供了这么多字幕源而且花了这么多空余时间翻译

**Comment by superk589** [comment]
申请翻译 600-1093

**Comment by ApolloZhu** [comment]
@superk589 欢迎回来。已经记上了

**Comment by VoiceBeer** [comment]
@ApolloZhu  第五课中他有讲五个 MVC 控制器，例如 navigation controller 这样的。你觉得是翻译成导航控制器呢还是直接保留不翻译好呢？

**Comment by ApolloZhu** [comment]
第一个同时保留中英文，其余的建议：概念性的用导航控制器，涉及代码的用 UINavigationController。

**Comment by VoiceBeer** [comment]
好的

**Comment by CrowsStriker** [comment]
我来翻1400-1836吧。

**Comment by ApolloZhu** [comment]
好，注意两条字幕之间要留空行

**Comment by ApolloZhu** [comment]
@CrowsStriker 稍微统一一下翻译：

Split View 单独出现不翻译。
Split View Controller 在指类的时候（比如说到属性或方法）用 UISplitViewController，否则用分屏控制器

@superk589 你的部分只出现了一次（1025），就用 UISplitViewController
@LiulietLee 按照此标准校对 VoiceBeer 的 #32，尽量第一次翻译成分屏控制器的时候注明英文

<details>
<summary>这样决定的原因？</summary>
Split View 作为苹果在 iOS 和 macOS 上推出的功能，并没有得到翻译，所以单独出现的时候不翻译。
但上面提到的 Split View 一般被科技媒体翻译为分屏功能，所以 Split View Controller 在不涉及代码的部分，建议翻译为分屏控制器
</details>

**Comment by superk589** [comment]
好的

**Comment by VoiceBeer** [comment]
@ApolloZhu 我都是翻译成 视图分割控制器 的，用它检索改起来应该能快一些

觉得是不是可以开一个独立的 md 用于那些容易引起歧义的词的汇总？比如新的翻译好后，就在那个 md 里修改加上自己翻译里觉得可能会有歧义的特有术语的翻译，然后提交汇总，再统一修改，这样之后的翻译里如果再碰到的话可以直接查那个表？

**Comment by ApolloZhu** [comment]
我有这个想法（可能还要大胆一些），但目前就先像你之前问 Navigation Controller 一样在那一集下面问吧。
@VoiceBeer 你的部分就交给 @LiulietLee 校对的时候改就行了。

**Comment by VoiceBeer** [comment]
嗯，那行

**Comment by superk589** [comment]
请问 手势的 handler 应该如何翻译
如
```
662
00:30:06,172 --> 00:30:08,672
we're gonna put that handler in the view.
```

参考以往，iOS 9 的课程翻译为“处理器”，网上也有将其称作“句柄”的
我个人不太喜欢句柄的说法，但是貌似这才是最术语的叫法，术语表目前没有这个词

**Comment by ApolloZhu** [comment]
<details>
<summary>句柄指的是 handle, Windows 开发的名词，</summary>
Any token that a program can use to identify and access an object such as a device, a file, a window, or a dialog box.
</details>
而 handler 在这一集中可以指代一下几种：

1. gesture recognizer: （手势）识别器
2. target：（负责）处理（手势）事件的目标对象
3. action：（负责）处理（手势）事件的函数或方法

你这里的情况应该是指手势识别器
顺便提一下：存储 action 的变量官方翻译为 “存根”

**Comment by superk589** [comment]
还是不太明白，再举一个例子
比如一处讲解 demo 时
先写了一个方法
```
func changeScale(byReactingTo pinchRecognizer: UIPinchGestureRecognizer) {
       ...
}
```

然后说
```
685
00:31:14,973 --> 00:31:17,440
So this is gonna be my handler.
```
这里指的单单就是那个方法本身，此时还没有写```let pinchRecognizer = UIPinchGestureRecognizer(target: Any?, action: Selector?)```

**Comment by ApolloZhu** [comment]
嗯，看了一下，这里指的应该是方法本身

**Comment by superk589** [comment]
句柄确实是我理解错了，感谢纠正
之前的课程将这个方法翻译成是手势的“处理器”，但是感觉没能很好表达这个意思，如果翻译成“响应方法”或“回调方法”怎么样，或者保持原文 handler？

**Comment by ApolloZhu** [comment]
如果在说明这个方法的作用，建议跟着微软翻译成 ”处理方法“
如果在说明这个方法是怎么被调用的，这种情况可以翻译为 “回调方法”
<details>
<summary>微软术语集 handler 具体翻译</summary>

![image](https://user-images.githubusercontent.com/10842684/29741751-980e1478-8a40-11e7-9a21-c3b9631c7ebb.png)
</details>
