### ISSUE TITLE
领任务前先看这里

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#2]
现在已转移至 https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/CONTRIBUTING.md

## 怎么领任务？

1. 每节新内容发布以后，我都会在这里开一个当节的「任务分配」issue
2. 想要领任务的同学，自愿到那个 issue 中 comment「翻译」或「校对」，进入队列。
3. 在你被分配到任务后我会在 issue 中 @你。如果有特殊通知时间段（海外党，只有周末的学生党等），请在 comment 中注明时区或特殊时间段。
3. 为了兼顾翻译的效果和参与度，我将进行AB测试，每次任务目前会考虑分成在 500 和 300 条左右两种，你可以选择在 comment 中注明更倾向于哪一种。你可以先自己翻译一小段试试，看看需要多长时间。我自己是 50 行／小时。
4. 对于之前 iOS 8 和 9 排队但没有接到任务的各位，因为我没有之前的队列，目前我表示没有办法优先考虑。

## 如果有了任务我该做什么？

1. 在 comment 中回复表示收到任务，或发邮件到 public-apollonian@outlook.com（请表明 GitHub 用户名、集数、行数）。
2. 接收到任务24小时之内未能联系我的，视为放弃任务，请重新排队。
3. 确认后**项目管理员**会更新在 issue 顶部的状态，并更新 [看板](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/projects/1)。
4. 翻译时先 fork 到你的账户下，翻译 subtitles 文件夹下对应的 srt 文件，翻译完后再提 pull request 回来。
5. 翻译和校对的过程中有拿不准的地方，进入该节的 issue 中讨论（如这个词该不该翻译，该翻译成什么等），也可以在翻译处标记 `<##>`，并在 pull request 中提出

## 任务的期限

1. 每 300 或 500 条字幕目前都是有 7 天的时间提交，我将根据测试结果调整。
2. 如果忙碌或者有困难一定要及时提出来，不必害羞。为了大家的利益我将会把任务转给其他人。

### 翻译、校对任务的序号不是指字幕文件中行数，而是指

```
67 <----此处的数字
 00:03:04,860 --> 00:03:06,960
 we talked about the NSNumber format and all that.
```

本规则基于 https://github.com/SwiftGGTeam/Developing-iOS-9-Apps-with-Swift/issues/3 修订而成。

**Comment by Sat-ice** [comment]
iOS已经过气了🌹🐔

**Comment by ApolloZhu** [comment]
规则转移到 https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/CONTRIBUTING.md
