### ISSUE TITLE
请问这个项目还在继续翻译中吗

### ISSUE THREAD

**Issue by Wanguy** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#22]

**Comment by ApolloZhu** [comment]
问的很好，正好能加到常见问题里
回答：在（你看 [活跃度](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/pulse) 还是有的）
内幕：我还指望着去 Stanford 呢

**Comment by Wanguy** [comment]
那太好了，英语水平一般，只能在背后默默支持了，真希望有什么能帮助到你们的。

**Comment by CoderLGL** [comment]
@ApolloZhu 关于捐助弄好了吗,希望给你们一些实质的帮助

**Comment by ldsea** [comment]
同问

**Comment by ApolloZhu** [comment]
@CoderLGL @ldsea https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/SUPPORT.md#为什么捐助一直在拖
还是先谢谢大家了，现在还是先以翻译为主吧。
