### ISSUE TITLE
「任务分配」1. Introduction to iOS 10, Xcode 8 and Swift 3

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#3]
|字幕序号|翻译人员|状态|校对人员|状态|
|--|--|--|--|--|
|1-300|@ApolloZhu|完成||待认领|
|301-804|@ApolloZhu|完成||待认领|
|805-1100|@ApolloZhu|完成||待认领|
|1101-1625|@ApolloZhu|完成||待认领|

**Comment by ApolloZhu** [comment]
这好好的硬盘又出问题了。。。我翻译的字幕啊
是我mac的使用方式哪里有问题么

**Comment by dashgeng** [comment]
第一集看了一遍，有几处明细错误，但不影响内容理解，望加快翻译速度！

**Comment by ApolloZhu** [comment]
@dashgeng 能帮忙改改，或者说一下哪里有问题吗
