### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by asood123** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#36]
Hi there - 

Thanks for applying to create an Open Collective. Could you tell us a little about what you plan to use the money for? And if you are ok with receiving money in USD only?

Thanks
Aseem

**Comment by 01jedi** [comment]
Hi Apollo
Currently I'm a student of Electronics engineer in UC(university of
Canterbury in New Zealand) also a Parttime tutor for the undergraduate
students.Apply that money for the apple developers account and hardware for
the future studying and researching  .Should be fine with USD.

Thanks
Alex
希望能够加入字幕组 帮助大家  传道授业 尽我所能 科技改变世界。XD

2017-10-12 22:38 GMT+08:00 Aseem Sood <notifications@github.com>:

**Comment by ApolloZhu** [comment]
@asood123 Hi, Aseem. This project is aimed to translate subtitles of stanford cs193p from English to Chinese. *Those people who benefited from our work would like to thank us by donating some money*, as said in #12. Using Open Collective is **intended to be for USD**, and we'll use WeChat/Paypal for CNY. **How we are going to use the money is not yet determined, but the current plan is to either distribute the money to contributors, or to purchase paid translations to boost the translation process.**

Thank you for reaching out to us, and sorry for the inconvenience.

Sincerely,
Apollo Zhu
Project Owner

**Comment by ApolloZhu** [comment]
@01jedi https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/CONTRIBUTING.md

**Comment by asood123** [comment]
Sounds good, I'll set you up now.
