### ISSUE TITLE
为何没有人翻译了，这个项目关注的人好少啊

### ISSUE THREAD

**Issue by l5ee** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#4]
英文太差，也不知道怎么帮忙啊，不太懂怎么用github和翻译，校对

**Comment by ApolloZhu** [comment]
关于翻译，我明天放假，会继续的

至于为什么没人，原因如下

1. 我个人影响力不够
2. 我还没有在原来的 QQ 群和项目里说有这个项目
3. 我还没有尝试过推广

如果您觉得无法参与到翻译与校对的过程，您也许可以帮忙推广

**Comment by superk589** [comment]
@ApolloZhu 请问如何参与到这个项目呢 个人有一些闲散时间可以用来翻译 不过看到工作量有点巨大 请问有没有用来讨论的QQ群之类的地方

**Comment by ApolloZhu** [comment]
@superk589 如果觉得一周五百行有点多，三百行应该还是可行的。
参与项目请参考 #2 ，和项目的 README。
讨论的QQ群暂时没有，如果有什么要紧事可以直接留 issue

**Comment by superk589** [comment]
@ApolloZhu  好 明白了 我一旦准备开始弄 会接任务并联系你的

**Comment by lianfanghua** [comment]
@l5ee 从这个课程发布我就在关注，我看网易公开课上也有不少人希望能跟进ios10的课程翻译，很艰难的找到了这里，从我的经历上来看，不是没人关注，是找不到如何关注。我也尝试过自己翻译，也是用ccextractor，字幕也抓到了，也尝试翻译了第一集，但是现在跟 @ApolloZhu 翻译的对比下，觉得自己的英文太差了。这个课程是个好课程，不管什么原因，希望你们能坚持翻译，起码我身边有几个朋友都在等待着，关注度没有你们想象中这么低。加油。

**Comment by ApolloZhu** [comment]
@lianfanghua 谢谢！
我试过在网上找，GitHub 和 Google 的搜索结果都是靠前的，就是百度找不到。如果真要说关注的话，我觉得 **点击 Star** 是个好方法。关于推广和关注没说清楚，我之后会补上去。
如果您愿意的话，可以考虑帮着翻译一部分，到时候再改改都行。毕竟大家精力和时间都有限（特别是我最近要期末考试），还是人多力量大。

**Comment by aptx876** [comment]
ios10 的变换很大，以前的课程已经有些不太合适了，这个课程应该目前最好的ios课程

我最近一直在看您的字幕，无奈自己的英语水平太差帮不上忙，希望楼主能够坚持下去把字幕做完

**Comment by ApolloZhu** [comment]
@aptx876 谢谢督促，现在考完了我倒是有时间上课摸鱼翻译。
同时希望您能通过 Star 这个项目支持我们。

**Comment by aptx876** [comment]
我觉得可以先用google翻译一下，虽然质量可能不会太理想，但是却可以先把整体快速的翻译出来，这样才能吸引更多人来看。翻译质量可以在后期看的过程中慢慢的去完善嘛

**Comment by ApolloZhu** [comment]
翻译本身不花时间，花时间的是要对照视频——很多句子离开语境之后像是看天书。

现在想想影响力不够应该是百度搜不到的锅。
![Referring sites](https://cloud.githubusercontent.com/assets/10842684/25689887/d2960966-3059-11e7-9ed5-456f81256b7b.png)

**Comment by aptx876** [comment]
确实，我也是偶然之间发现的。百度上确实不太好找。

不过我始终觉得这是最好的ios开发课程，虽然英语关难过，但是绝对不会误人子弟

**Comment by l5ee** [comment]
我现在看ios8那个教程是不是不合适了，因为那个是唯一翻译比较完整的了😳。试着英文下看了10的第二课，很吃力。。。

**Comment by ApolloZhu** [comment]
当年的大神们还在翻译 iOS 9...
确实 Swift 还没稳定下来，处于变化很大的阶段，督促大家认真学习更上步伐。不过过时的内容并不等于没有价值。我用另外一个例子，WWDC 的视频。很多年前的就算不再适用，看完之后也是有收获的。

**Comment by l5ee** [comment]
我比较担心ios8 很多语法和现在不一样了。好像swift3改变很多呢。我看计算器写法都有很多不同

**Comment by aptx876** [comment]
ios8那个课程的代码在最新的xcode里已经无法编译了，目前国内对于swift的学习远远比不上其他语言，要想系统化的把swift学习继续下去，只能来啃这个ios10的课程。

所以衷心希望朱老师能把翻译项目坚持下去。

**Comment by lianfanghua** [comment]
最近工作家庭都有点忙，就先不领任务了，抽空我在看CS106A和B的视频，还不错，毕竟是这个教程的前置条件

**Comment by l5ee** [comment]
额，那我放弃看iOS8了，直接啃10吧，我udemy上我看了一个weiwei的swift教程，是个台湾人的教程

**Comment by Xlff** [comment]
为啥iTunes里面的视频不更新了呢，而这能下载到最新的

**Comment by ApolloZhu** [comment]
这是 iTunes 的锅，这边的数据也只是从 [RSS 源](https://p1-u.itunes.apple.com/WebObjects/LZStudent.woa/ra/feed/COETAIHAJLZIQXJI) 抓的，你可以去看[代码](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/tools/main.swift)
