### ISSUE TITLE
「任务分配」2. MVC; iOS, Xcode and Swift Demonstration

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#5]
|字幕序号|翻译人员|状态|校对人员|状态|
|--|--|--|--|--|
|1-399|@ApolloZhu|完成||待认领|
|400-799|@lianfanghua|完成||待认领|
|800-1300|@ApolloZhu|完成||待认领|
|1301-1605|@ApolloZhu|完成||待认领|

**Comment by Sat-ice** [comment]
我想从第三集开始翻译可以吗，第二集我都看吐了，再看受不了😂

**Comment by lianfanghua** [comment]
我先领个400-799尝试下翻译，翻译可能会很烂，望见谅

**Comment by ApolloZhu** [comment]
好 @lianfanghua

**Comment by lianfanghua** [comment]
@ApolloZhu 确认收到

**Comment by lianfanghua** [comment]
412-415行
The other difference, huge difference, and the one that's gonna take the most getting used to for you conceptually is that classes live in the heap, and you have pointers to them.

另一个区别，巨大的区别，从概念上最常见的就是，类在堆中，有指针指向它。

这样翻译对么？

**Comment by ApolloZhu** [comment]
412
00:20:38,372 --> 00:20:41,239
so that's one difference. The other difference,
这是其一。另外一个区别

413
00:20:41,308 --> 00:20:42,073
huge difference, and
更本质的区别

414
00:20:42,142 --> 00:20:44,343
the one that's gonna take the most getting used to for
也是你需要理解的概念

415
00:20:44,411 --> 00:20:49,180
you conceptually, is that classes live in the heap, and
类存储在堆中

416
00:20:49,249 --> 00:20:53,151
you have pointers to them. Structs do not live in
通过指针传递。结构体存储在栈上

417
00:20:53,220 --> 00:20:58,156
the heap, and they are passed around by copying them, okay?
和类不一样，通过拷贝值传递

**Comment by lianfanghua** [comment]
好的，看得出来我翻译还是很生硬

**Comment by xuekedou** [comment]
我领一个800-1300的翻译吧。

**Comment by ApolloZhu** [comment]
好，谢谢

**Comment by ApolloZhu** [comment]
@xuekedou 能咨询一下什么情况么？

**Comment by xuekedou** [comment]
最近三个礼拜在准备学校的期末考试和社团的各种活动。翻译过程有点停滞。接下来两周学校要进行期末考试。可能要到7月才有时间。要不先把我的任务撤销吧，7月有时间我在加入。真的不好意思。

**Comment by ApolloZhu** [comment]
没关系，可以理解，等你有空欢迎再加入
如果之前有翻译一部分就先提交吧，没有就算了

**Comment by xuekedou** [comment]
暂时没有。
