### ISSUE TITLE
请问这句怎么翻译好呢？

### ISSUE THREAD

**Issue by lianfanghua** [ApolloZhu/Developing-iOS-10-Apps-with-Swift#7]
The other difference, huge difference, and the one that's gonna take the most getting used to for you conceptually is that classes live in the heap, and you have pointers to them. 

另一个区别，巨大的区别，从概念上最常见的就是，类在堆中，有指针指向它。

这样翻译对么？

**Comment by ApolloZhu** [comment]
1. 请到相关的集数下面问，便于管理
2. 正在上课，稍微晚点回

**Comment by lianfanghua** [comment]
好的
